---
title: "Project"
author: "Julia English"
date: "2022-09-22"
output: pdf_document
---
Does the state of a respondent's health affect their belief in the importance of politics. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading the library}
rm(list = ls())
library(ggplot2)
library(tidyverse)
library(dplyr)
library(foreign)
wvs <- read.dta('wvs_class.dta')

```

```{r}
unique(wvs$health)
unique(wvs$important_politics)
wvs_us <- wvs %>%
  filter(country == "United States") %>%
  select(health, important_politics)

wvs_us <- wvs_us %>%
  mutate(health_simp = if_else(health %in% c("Very good", "Good", "Fair"), 1, 0))

wvs_us <- wvs_us %>% 
  mutate(pol_simp = if_else(important_politics %in% c("Very important", "Rather important"), 1, 0))

health_prop_table <- wvs_us %>% 
  select(health_simp) %>%
  table() %>%
  prop.table()
         
knitr::kable(health_prop_table, digits = 3)

pol_prop_table <- wvs_us %>%
  select(pol_simp) %>%
  table() %>%
  prop.table()

knitr::kable(pol_prop_table, digits = 3)

  
```

```{r univariate bar graphs}
pol_bar <- wvs_us %>%
  mutate(pol_simp_2 = if_else(pol_simp == 1, "Politically Involved", "Politically Uninvolved")) %>%
  group_by(pol_simp) %>%
  ggplot(mapping = aes(x = pol_simp_2)) +
  geom_bar(fill = "dodgerblue", color = "black") +
  theme_dark() +
  labs(title = "Political Sentiments of Americans", x = "Political Importance", y = "Count")

pol_bar

health_bar <- wvs_us %>%
  mutate(health_simp_2 = if_else(health_simp == 1, "Healthy", "Unhealthy")) %>%
  group_by(health_simp) %>%
  ggplot(mapping = aes(x = health_simp_2)) +
  geom_bar(fill = "darkseagreen1", color = "black") +
  theme_dark() +
  labs(title = "Health Sentiments of Americans", x = "Overall Health", y = "Count")

health_bar
```

```{r}
health_data_frame <- health_prop_table %>% data.frame()

h_col <- health_data_frame %>%
  ggplot(mapping = aes(x = health_simp, y = Freq)) +
  geom_col(fill = "deeppink")

h_col


politics_data_frame <- pol_prop_table %>% data.frame()

p_col <- politics_data_frame %>%
  ggplot(mapping = aes(x = pol_simp, y = Freq)) +
  geom_col(fill = "steelblue3")

p_col
```


